### PR TITLE
m.joongna.com - Ad

### PR DESCRIPTION
**Pull request by green1052**
[URL](https://m.joongna.com/search-list/product?searchword=g903)

image

### CODE REVIEW

**Comment by seia-soto** [comment]
Currently we have some problem on the commit.

You're using extended CSS rule `:has` which is actually available on CSS spec version 4.

Please, move the rule or replace with following possible rules without extended CSS support:

```css
##div[class^="SearchList_powerLinkWrap"]
```

```css
##article[class^="SearchList_listWrap"] + div
```

Or should be the following form if you want to move the rule to extended_css_ELEMHIDE.txt.

```css
m.joongna.com#?#div:has(> div[class*="powerLinkWrap"])
```

**Comment by green1052** [comment]
ed8c585

**Review by seia-soto — APPROVED** [review]

**Review by piquark6046 — COMMENTED** [review]
I think that this issue can be also resolved by adding some `scriptlet` rule.
Please wait until I check.

<details>
<summary>Screenshot</summary>

Screensh222ot

</details>

**Comment by green1052** [comment]
search-api.joongna.com data.items

**Comment by green1052** [comment]
image

image

**Comment by piquark6046** [comment]
I cloud not find the javascript file named `NaverPowerShoppingList.js`.

<details>
<summary>Screenshot</summary>

Screensho

</details>

**Comment by green1052** [comment]
image

image

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/pull/290#issuecomment-1100883815
Thanks. I found.

**Review by piquark6046 — APPROVED** [review]
Cannot access the mentioned property using `scriptlet`.

**Pull request merged**
