### PR TITLE
dcinside app video error

### PR DESCRIPTION
**Pull request by green1052**

### CODE REVIEW

**Review by piquark6046 — CHANGES_REQUESTED** [review]
Is the video of a dcinside post loaded via HTTP protocol (Not HTTPS)?

**Comment by green1052** [comment]
Screenshot_20220430-235636_AdGuard

**Review by piquark6046 — COMMENTED** [review]
Can you provide URL of the dcinside post privately via email?

**Comment by green1052** [comment]
sent

**Comment by green1052** [comment]
this error only reproduce dc app

**Comment by piquark6046** [comment]
The similar request also exists on responsive design mode of Firefox desktop.
I will test with AdGuard for Windows.

**Review by piquark6046 — APPROVED** [review]

**Pull request merged**
