### PR TITLE
Rename from lightway to filters

### PR DESCRIPTION
**Pull request by piquark6046**
I believe that many rules in List-KR are outdated, and It is require to optimize and redesign many rules for each platform of AdGuard (e.g. `#%#//scriptlet()`, `$redirect` and merging). 

If you disagree my opinion because of low amount of rules, please leave a comment or changes request.

### CODE REVIEW

**Comment by green1052** [comment]
lgtm

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/pull/234#issuecomment-1065870317 @green1052 
If you want to approve it, please read [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

**Review by green1052 — APPROVED** [review]

**Review by seia-soto — APPROVED** [review]

**Comment by seia-soto** [comment]
Additionally, please consider calculating and announcing to users about this changes.

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
> Additionally, please consider calculating and announcing to users about this changes.

^

**Pull request merged**
