### PR TITLE
feat: adshield (first auto-heuristic patch)

### PR DESCRIPTION
**Pull request by seia-soto**

### CODE REVIEW

**Comment by seia-soto** [comment]
I am not removing innerHeight rule in this case as it's not problematic even now. Also, they can revert into previous version without any doubt.

**Review by piquark6046 — COMMENTED** [review]
Is `#%#//scriptlet("set-constant", "innerHeight", "undefined")`  no longer required?

**Comment by seia-soto** [comment]
Yes, the rule is not required anymore. You can delete it. It depends on your decision.

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/pull/298#issuecomment-1106685055
Okay. I will leave them.

**Review by piquark6046 — CHANGES_REQUESTED** [review]
`#%#//scriptlet("set-constant", "outerHeight", "0")` is required to block Ad-Shield on tgd.kr.

**Comment by seia-soto** [comment]
Ah, right. I thought they've removed the ad since last time I visited.

**Review by piquark6046 — APPROVED** [review]

**Pull request merged**
