### PR TITLE
ad: boannews.com

### PR DESCRIPTION
**Pull request by seia-soto**
URL: https://www.boannews.com/media/view.asp?idx=109607

### CODE REVIEW

**Comment by seia-soto** [comment]
@piquark6046 Is the branch protected? I can merge the commit without any approval.

**Review by piquark6046 — CHANGES_REQUESTED** [review]
Please check the following screenshots:
<details>
<summary>Screenshots</summary>

Screenshot from 2022-09-05 08-31-47
Screenshot from 2022-09-05 08-32-05


</details>

**Comment by piquark6046** [comment]
> Is the branch protected? I can merge the commit without any approval.

<details>
<summary>branch protection rules</summary>

dfgdf


</details>

**Comment by seia-soto** [comment]
Closing as duplicate.

**Comment by seia-soto** [comment]
@piquark6046 Thanks for letting me know! I think the filter set was unexpectedly unloaded somehow.

**Pull request closed without merging**
