### PR TITLE
Create List-KR experimental

### LINKED ISSUE #411: (제안) 애드쉴드/나무위키 필터를 별도 파일로 분리하면 어떨까요?
현황
=====
현재 List-KR에서 애드쉴드와 나무위키의 파워링크 광고를 차단하고자 많은 노력을 하고 있고, 이들 웹 사이트 역시 이를 그냥 두지 않고 지속적으로 우회하고 있습니다. 그런데, 일단 우회를 하고나면 단순히 광고가 다시 나타나는 정도가 아니라 이미지가 사라지거나, 페이지의 내용이 사라지거나, 로딩속도 저하등의 현상이 자주 발생하다보니 오히려 광고보다 더 불편하게 되는 부작용이 발생하고 있습니다. 이 때 유저 입장에선 문제가 있는 필터만 골라서 끄는 방법이 없기 때문에 응급조치를 위해...
* 나무위키에서 애드블락을 해제 (이러면 구글광고 등 잘 막던 광고도 놓치게 됨)
* List-KR 필터를 비활성화 (이러면 다른 한국어 웹사이트도 전부 영향 받음)

하는 경우가 생깁니다.

제안
=====
List-KR의 필터 중 **특히 오작동이 자주 발생하는 필터만 별도의 파일로 분리**하는 방안은 어떨까요? 이렇게하여 오작동 발생시 응급조치로써 **유저에게 하여금 문제있는 필터만 개별적으로 끌 수 있는 방법**이 생기게 됩니다.

방안 1
-----
기존 필터에서 오작동이 잦았던 필터를 다음과 같이 둘로 나눕니다.
* List-KR (기존 필터에서 오작동 발생이 잦았던 부분이 없는 버전)
* List-KR Advanced (가칭) (애드쉴드와 나무위키 등 오작동이 많았던 버전. 유저는 웹 사이트 문제 발생시 응급조치로 이 필터만 끌 수 있도록.)

방안 2
-----
위와 비슷하나 애드쉴드와 나무위키를 별개로 분리하여 셋으로 나눕니다. 파일이 많아지긴 하나 유저 입장에선 나무위키나 애드쉴드 둘 중 한가지만 끌 방법이 생기게 됩니다.
* List-KR
* List-KR for Ad-Shield
* List-KR for NamuWiki

### PR DESCRIPTION
**Pull request by piquark6046**
## [나무위키 하단 파워링크 광고와 애드쉴드 문제 해결하기](https://github.com/List-KR/List-KR/wiki/%EC%9C%A0%EC%A0%80%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-%EC%84%A4%EC%B9%98-(AdGuard))

---

Resolve https://github.com/List-KR/List-KR/issues/411.

### CODE REVIEW

**Comment by piquark6046** [comment]
@gaeulbyul

**Review by green1052 — APPROVED** [review]
lgtm

**Comment by gaeulbyul** [comment]
👍 파일이 따로 나뉘게 된 만큼 README에 해당 필터를 설치하는 방법에 대한 안내가 있다면 더 좋을 거 같아요.

**Comment by green1052** [comment]
what's min value for Expires header?

if less 1 day better set 1 hour

**Comment by JobcenterTycoon** [comment]
So we have the regular filter and the experemential one and the user need to import the experemential one?

Im wondering why all redirect and whitelist filter get moved too because they aren’t problematic. The only problematic filter for Ad-Shield i see are:

```
/:\/\/[a-z\.]+\/[a-zA-Z\.\_]{1,30}\/[a-zA-Z\.\_]{1,30}\/[a-zA-Z0-9\.\_\/]+\.(eps|jar|pls|pict|xls|xlsx|mid|midi|avif|pdf|ps|webp|ppt|csv|doc|docx|tif|tiff|class|pptx)$/$doc,popup,inline-script,1p,domain=ppss.kr|ygosu.com|loawa.com|feedclick.net|dailian.co.kr|inven.co.kr
/:\/\/[a-z\.]+\/[a-zA-Z0-9]{10,15}\.(eps|jar|pls|pict|xls|xlsx|mid|midi|avif|pdf|ps|webp|ppt|csv|doc|docx|tif|tiff|class|pptx)$/$doc,popup,inline-script,1p,domain=ppss.kr|ygosu.com|loawa.com|feedclick.net|dailian.co.kr|inven.co.kr
/:\/\/[a-z\.]+\/[a-zA-Z\.\_]{1,15}\/[a-zA-Z0-9\.]{5,25}\.(eps|jar|pls|pict|xls|xlsx|mid|midi|avif|pdf|ps|webp|ppt|csv|doc|docx|tif|tiff|class|pptx)$/$doc,popup,inline-script,1p,domain=ppss.kr|ygosu.com|loawa.com|feedclick.net|dailian.co.kr|inven.co.kr

loawa.com,ppss.kr,feedclick.net,ygosu.com##style+div:nth-last-child(1)
loawa.com,ppss.kr,feedclick.net,ygosu.com#$#div[id]>div[id]>img[src] { display: none; }
```

@green1052 uBO will round it to 1 day

**Comment by piquark6046** [comment]
> So we have the regular filter and the experemential one and the user need to import the experemential one?

No. Importing the experemential one does not required.
I and @gaeulbyul hope that these changes make a user keeping List-KR in their filters list.

If a user want to block these advertisement, the user can add [microShield](https://github.com/List-KR/microShield) or [NamuLink](https://github.com/List-KR/NamuLink) into their userscript manager. 

> Im wondering why all redirect and whitelist filter get moved too because they aren’t problematic. The only problematic filter for Ad-Shield i see are:

A `$redirect-rule` filter can be detected by measuring the size of responded data.

**Review by ghost — APPROVED** [review]

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/pull/412#issuecomment-1156573507
@JobcenterTycoon

**Review by seia-soto — COMMENTED** [review]
In case of, if we have a proper CI system for commenting the rules marked automatically, we can have an opt-out approach for users to try to block the ads by default. Lay people don't see the these mechanism in general.

I am requesting some changes:

1. Additional description for List-KR Experimental.

We need a proper reason for users. For example:
- All AdShield and NamuWiki related rules are moved to experimental filter to resolve high rate of rule resulting false-positive.
- You can **opt-in** to these rules to block ads on complex sites using **only AdBlocker rules** by adding List-KR experimental.

2. Listing method

List-KR experimental is the filter that can be handled actively not only maintainers but also outside collaborators of List-KR. How about making it more describable by adding some issue URLs?

Partially, I basically agree with @JobcenterTycoon and want to leave non-problematic rules. However, to make the situation clear for lay people, I think we need to completely detach the rules.

**Review by JobcenterTycoon — APPROVED** [review]

**Review by seia-soto — APPROVED** [review]

**Comment by piquark6046** [comment]
@seia-soto Please re-review https://github.com/List-KR/List-KR/commit/1c77f4a1431665764aca99b0e69cc2148ea17dd4.

**Comment by seia-soto** [comment]
> @seia-soto Please re-review [1c77f4a](https://github.com/List-KR/List-KR/commit/1c77f4a1431665764aca99b0e69cc2148ea17dd4).

I agree with you. Sorry for recent late replying. But I think I'll delay some development works next 2 weeks (maybe). School test period is coming.

**Comment by JobcenterTycoon** [comment]
Better is to move a filter back to the regular one:

`loawa.com#?##equip-info-modal:has(> .modal-dialog > .modal-content > .modal-body > button.close + button.float-right)` is needed to fix the broken overlay

**Pull request merged**
