### PR TITLE
fix namu.wiki

### PR DESCRIPTION
**Pull request by seia-soto**
In this time, I highly encourage removing the rule format starting with `article`

### CODE REVIEW

**Comment by seia-soto** [comment]
- https://github.com/AdguardTeam/AdguardFilters/issues/108883
- https://github.com/seia-soto/filter-kr/commit/89719e2dc9fe4ff7cd741998f7c77ee1fffe7341
- https://github.com/List-KR/List-KR/issues/236

**Review by piquark6046 — COMMENTED** [review]
I cannot reproduce it.

<details>
<summary>Screenshot</summary>

Screenshot

</details>

**Comment by seia-soto** [comment]
It's likely due to accumulated cookie of namuwiki which can be categorized to anti-adblocking skill.

image

Incognito tab of Chromium doesn't reproduce the problem, but still normal tab without cache can reproduce the problem.

**Comment by seia-soto** [comment]
Here is video that proves no cache was applied.

https://user-images.githubusercontent.com/30369714/165327656-0a26abab-17e6-44c9-94a0-315e9238ef9f.mov

By looking at the header `cf-cache-status: dynamic`, this is not from CloudFlare cache.

image

**Review by piquark6046 — COMMENTED** [review]
Still cannot reproduce.

<details>
<summary>Screenshot</summary>

Screenshot


</details>

**Comment by piquark6046** [comment]
https://listauthorschat.slack.com/archives/C010N14G4TF/p1650985112365639

**Review by piquark6046 — APPROVED** [review]
For now, I merge this PR.
Please continue this conversation in istauthorschat.slack.com.

**Comment by seia-soto** [comment]
Thanks. Posted proves.

**Pull request merged**
