### PR TITLE
remove unicon pro

### PR DESCRIPTION
**Pull request by green1052**

### CODE REVIEW

**Review by piquark6046 — COMMENTED** [review]
This is just a trap.

**Comment by green1052** [comment]
???

**Comment by piquark6046** [comment]
I meant that it exists in the issue templates to inform the above information when a List-KR filter user reports.

**Comment by green1052** [comment]
ok so plz merge only #7507267?

**Comment by piquark6046** [comment]
The `ad-block-user.yml` file is used for categorize.

**Comment by green1052** [comment]
ok

**Pull request closed without merging**
