### PR TITLE
ad: tfreeca22.com and family sites

### PR DESCRIPTION
**Pull request by seia-soto**
Report from anon. user. Specially in post viewing page.

### CODE REVIEW

**Review by piquark6046 — CHANGES_REQUESTED** [review]
A visitor is redirected to uuoobe.kr.

**Review by seia-soto — COMMENTED** [review]
chore: append www at the front

**Comment by seia-soto** [comment]
Still the site is redirected but you can access via `https://www.tfreeca22.com/main.php`.

**Comment by seia-soto** [comment]
Seems like the routing map configured as:
- / => redirect
- / + any chars => show page
- without-subdomain => prepend www and pass all arguments

**Comment by piquark6046** [comment]
Great. I visited successfully.

**Comment by seia-soto** [comment]
Yup, but do you think prepending the `www` at the front is reasonable?

**Comment by seia-soto** [comment]
Hm... At my point, I think the site looks like would change the domain name frequently and prepending www or not will not affect to the real users. I think both are ok.

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/pull/442#issuecomment-1185585371
If domain of the mobile version starts with `m.` and its DOM structure is similar, I don't want to add `www.`.

**Comment by seia-soto** [comment]
Confirmed. I agree to you.

**Comment by piquark6046** [comment]
@seia-soto 
Please try to search `i.uuoobe.com` in network section of your browser.
It seems strange.
<details>
<summary>Screenshot</summary>

Screensho23


</details>

**Comment by seia-soto** [comment]
I see images from `i.uuoobe.com` are common content. (when I enabled the filter)

<details>
<summary>Screenshot</summary>

image

</details>

**Comment by seia-soto** [comment]
Their download domain `filetender.com` seems like containing same ads and adding it... wait a sec.

**Comment by piquark6046** [comment]
I think that `uuoobe.com` and `tfreeca22.com` are operated by a same administrator because a visitor will be redirected to the website by clicking the following element:
<details>
<summary>Screenshot</summary>

Screenshot33

</details>

**Comment by seia-soto** [comment]
Also, it's same on `filetender.com`. I extracted the code from their website

<details>
<summary>Details</summary>

```html
<script>
function jump(){
    top.location.href='https://www.uuoobe.kr/main.php?ref=ten';
}    

$(function(){
    $("#TencentCaptcha").click(function(){
        var newUrl = 'https://file.filetender.com/Execdownload.php';
        $("#Down").attr('action',newUrl);
        $("#Down").submit();
        setTimeout(jump,15000);
		//hiddenframe.location.href="https://filetender.com/mobon3.php";
		
    })
})
</script>
```

</details>

**Comment by seia-soto** [comment]
Will take over to you. Almost 12 PM here.

**Review by piquark6046 — APPROVED** [review]

**Pull request merged**
