### PR TITLE
newspic.kr - Coupang read more advertisement

### PR DESCRIPTION
**Pull request by piquark6046**

### CODE REVIEW

**Comment by green1052** [comment]
not working
image

image

**Comment by piquark6046** [comment]
@green1052 
Please clear the cookie and site data, close the tab, and reopen it.

**Comment by green1052** [comment]
image

**Comment by green1052** [comment]
No change

**Comment by green1052** [comment]
localStorage.setItem(etcType === 'COUPANG' ? frequencyKey: frequencyKey2, new Date().getDate() + '');

how about add item

**Comment by green1052** [comment]
```js
    MoreRead = function() {
        var n, a = "npMoreRead",
            o = function() {
                $(".omit_wrap").removeAttr("style").removeClass("omit_wrap"), $('[data-role="btnMoreRead"]').remove(), n && n()
            };
        return {
            init: function(e) {
                var t;
                e && "function" == typeof e && (n = e), 0 < $('.omit_wrap [data-role="btnMoreRead"]').length ? ($('.omit_wrap [data-role="btnMoreRead"]').on("click", function(e) {
                    e.preventDefault();
                    var t, n = $(this).data("type");
                    "COUPANG" === n && (t = (new Date).getTime() + 18e5, NewspicStorage.set(a, t), NewspicWebLog.commonLog("CONTINUE-READING-COUPANG-CLICK", {}, function() {
                        location.href = "https://coupa.ng/b9PqdK", o()
                    })), "NORMAL" === n && NewspicWebLog.commonLog("CONTINUE-READING-CLICK", {}, function() {
                        o()
                    })
                }), "COUPANG" === $('.omit_wrap [data-role="btnMoreRead"]').data("type") && ((t = NewspicStorage.get(a)) && Number(t) >= (new Date).getTime()) && o()) : o()
            },
            remove: o
        }
    }(),
```

MoreRead func 

image

**Comment by green1052** [comment]
```js
   init: function() {
                if (0 !== $("#bo_v_atc").length) {
                    18 === Number($("#npLog").data("pn")) && (d = 0), $("#npLog").data("nid"), $("#bo_v_atc b,#bo_v_atc strong").each(function() {
                        $(this).css("font-weight", "bold")
                    }), 82 === Number($("#npLog").data("pn")) && ($("#bo_v_atc .naver_ad").remove(), $("#bo_v_atc .power_link").remove()), $(".aside_wrap > .box").each(function() {
                        $(this).hasClass("cmt_box_m") || ($(this).removeAttr("style"), 0 < $(this).find("ins.adsbygoogle").length && $(this).removeClass("box").addClass("googleAD_wrap"))
                    }), $(".aside_wrap > .list_widget iframe").each(function() {
                        $(this).removeAttr("width").removeAttr("height")
                    }), $("iframe.lazy").each(function() {
                        $(this).attr("src", $(this).data("src"))
                    }), $(".ga-open").on("click", function(e) {
                        e.preventDefault();
                        var t, n, a, o, i, r, c = !0;
                        $(this).hasClass("mobile-only") && (t = navigator.userAgent.toLowerCase(), n = /android/.test(t), a = /iphone|ipad|ipod/.test(t), n || a || (alert("모바일 디바이스만 지원되는 서비스 입니다."), c = !1)), c && (o = $(this).data("category"), i = $(this).data("action"), r = $(this).data("label"), ga("send", "event", {
                            eventCategory: o,
                            eventAction: i,
                            eventLabel: r
                        }), window.open($(this).attr("href")))
                    }), $("#bo_v_atc iframe,#bo_v_atc video,#bo_v_atc embed").each(function() {
                        $(this).parentsUntil("#bo_v_atc").each(function() {
                            $(this).removeAttr("style")
                        }), $(this).parent().hasClass("iframe_wrapper") || $(this).removeAttr("width").removeAttr("height").css("width", "100%").css("height", "100%").css("position", "absolute").wrap('<div class="iframe_wrapper" style="position:relative;width: calc(100% + 40px); margin: 0 -20px;height:0;padding-bottom:80%;"></div>');
                        try {
                            "video" === $(this).prop("tagName").toLowerCase() && $(this).attr("poster").startsWith("https://images-cdn.newspic.kr") && ($(this).css("position", "").css("height", "auto"), $(this).parent().css("height", "").css("padding-bottom", ""))
                        } catch (e) {}
                    }), $("#bo_v_atc img").each(function() {
                        $(this).removeAttr("style").removeAttr("srcset").removeAttr("width").removeAttr("height").removeAttr("sizes"), "FIGURE" === $(this).parent().prop("tagName") && ($(this).parent().prop("tagName", "div").addClass("image_view"), $(this).parent().find("figcaption").addClass("caption")), $(this).parentsUntil("#bo_v_atc").each(function() {
                            $(this).removeAttr("style")
                        });
                        try {
                            0 === $(this).attr("data-original").indexOf("https://www.webtoonguide.com/api/rss/check.gif") && $(this).css({
                                width: "1px",
                                margin: "0"
                            })
                        } catch (e) {}
                    });
                    try {
                        PinchToZoom.init()
                    } catch (e) {}
                    MoreRead.init(function() {
                        var e, t, n, a, o, i;
                        r(), c(), 0 < $("#bo_v_atc blockquote.instagram-media").size() && ((e = document.createElement("script")).src = "//www.instagram.com/embed.js", document.querySelector("head").appendChild(e)), 0 < $("#bo_v_atc blockquote.twitter-tweet").size() && ((t = document.createElement("script")).src = "https://platform.twitter.com/widgets.js", document.querySelector("head").appendChild(t)), 0 < $("#bo_v_atc blockquote.tiktok-embed").size() && ((n = document.createElement("script")).src = "https://www.tiktok.com/embed.js", document.querySelector("head").appendChild(n)), 0 < $("#bo_v_atc blockquote.reddit-card").size() && ((a = document.createElement("script")).src = "https://embed.redditmedia.com/widgets/platform.js", document.querySelector("head").appendChild(a)), "" !== (o = $("<div />").html($("#first-image-ad").html()).text()) && "\x3c!-- 미사용 --\x3e" !== o && 18 !== Number($("#npLog").data("pn")) && $("#bo_v_atc img").each(function(e, t) {
                            0 === e && (0 < $(this).closest("figure").length ? $(this).closest("figure").append(o) : $(this).parent().append(o))
                        }), "" !== (i = $("<div />").html($("#second-image-ad").html()).text()) && "\x3c!-- 미사용 --\x3e" !== i && 18 !== Number($("#npLog").data("pn")) && $("#bo_v_atc img").each(function(e, t) {
                            1 === e && (0 < $(this).closest("figure").length ? $(this).closest("figure").append(i) : $(this).parent().append(i))
                        })
                    }), 457 === Number($("#npLog").data("pn")) && ($("#bo_v_atc img").each(function() {
                        $(this).data("original") && 0 <= $(this).data("original").indexOf("a1.api.bbc.co.uk/hit.xiti") && $(this).remove()
                    }), $('<img src="" alt=""/>').attr("src", "https://a1.api.bbc.co.uk/hit.xiti?library_version=synd_nojs&s=598346&p=" + encodeURIComponent($('meta[property="og:title"]').attr("content")) + "&site_level2=Korean&app_type=responsive&app_name=newspic&idclient=" + NewspicCookie.get("newspicPCID") + "&partner_id=" + encodeURIComponent("newspic.kr")).appendTo("body")), $("#bo_v_atc img.lazy").lazyload(), $("#share-content-text").on("click", function(e) {
                        e.preventDefault();
                        var t = $(this).attr("href");
                        NewspicGA.open("파트너스 공유 안내 문구 클릭", null, null, t)
                    })
                }
            }
```

**Comment by piquark6046** [comment]
@green1052 Please re-review.

**Comment by green1052** [comment]
```
newspic.kr#%#//scriptlet("remove-attr", "data-cp|data-cp-name|data-first-cp", "input#npLog", "stay")
```

rule is not working in chrome, firefox

test url
https://m.newspic.kr/view.html?nid=2022041113071579592&pn=314&cp=N6WRI99f

**Comment by piquark6046** [comment]
@green1052 Did you clear web browser cache?

**Comment by green1052** [comment]
Actually i am use alway private mode ;(

**Comment by piquark6046** [comment]
@green1052

**Review by green1052 — APPROVED** [review]
lgtm

**Pull request merged**
