### PR TITLE
www.daum.net - Ad

### PR DESCRIPTION
**Pull request by green1052**
https://github.com/AdguardTeam/AdguardFilters/issues/116597

### CODE REVIEW

**Review by piquark6046 — COMMENTED** [review]
Did you log in to daum.net?

**Comment by green1052** [comment]
no i didnt

**Review by piquark6046 — CHANGES_REQUESTED** [review]
Your suggested rule is duplicate of `www.daum.net##div[class^="advert_"]`.
Can you check again?

<details>
<summary>Screenshot</summary>

Screenshot

</details>

**Comment by green1052** [comment]
sry i forget class attr

**Pull request closed without merging**
