### PR TITLE
Ad-Shield

### PR DESCRIPTION
**Pull request by JobcenterTycoon**
Fixed Ad-Shield on `dailian.co.kr`

### CODE REVIEW

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/277

**Review by piquark6046 — APPROVED** [review]

**Comment by ReveLovy** [comment]
Ad Shield is back. What's more important is that when I use AdGuard, there was a bug on the website, so I couldn't use it. Originally, after I click on a link in Loawa, a modal window appears, and then I press Close to disappear. However, when I use AdGuard, I can't close it after pressing Close and a strange model window appears. The site creator only tells me to turn off the AdGuard. When i add custom rule

loawa.com#@%#//scriptlet("prevent-setTimeout", "", "10")
loawa.com#@%#//scriptlet("prevent-setTimeout", "", "10")
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=loawa.com
@@||ad.doubleclick.net/ddm/adj/Bkne/Bdfs$domain=loawa.com

And the ad-shield didn't show up and the weird model window disappeared.
I don't know about HTML, but it was solved due to the addition of the above filter (exception).
I'd appreciate it if you could check. thx
(With the above filter (exception), the Modal Window has disappeared, but it appears once in 10 times.)

**Comment by seia-soto** [comment]
I am working on it as part-time since it's not my primary job. Thanks for your suggestion, I'll try to build a rule based on yours.

> I forwarded your message to internal chat so we can mitigate.

**Comment by JobcenterTycoon** [comment]
> What's more important is that when I use AdGuard, there was a bug on the website, so I couldn't use it. Originally, after I click on a link in Loawa, a modal window appears, and then I press Close to disappear. However, when I use AdGuard, I can't close it after pressing Close and a strange model window appears.

I get this even without adblocker
Unbenannt

Refresh a few times to make the adcrap dissappear and its fine

**Pull request merged**
