### PR TITLE
gigglehd.com - Ad

### PR DESCRIPTION
**Pull request by piquark6046**
https://gigglehd.com/gg/
https://gigglehd.com/gg/bbs/11965681

---

https://github.com/List-KR/List-KR/issues/248
https://github.com/AdguardTeam/AdguardFilters/issues/113454

### CODE REVIEW

**Comment by piquark6046** [comment]
@green1052 
@seia-soto

**Comment by green1052** [comment]
i cant test now sry

**Review by green1052 — APPROVED** [review]

**Comment by green1052** [comment]
lgtm

**Comment by seia-soto** [comment]
@piquark6046 Sorry, but please give the priority to green1052 or Raiden-Ei. I cannot check regularly as I am treating of COVID19.

**Pull request merged**
