### PR TITLE
fix 11st app sk pay error

### PR DESCRIPTION
**Pull request by green1052**

### CODE REVIEW

**Comment by piquark6046** [comment]
What does a stealth configuration cause your issue?

 - https://github.com/AdguardTeam/CoreLibs/issues/1224

**Comment by green1052** [comment]
idk maybe cookie?

**Comment by piquark6046** [comment]
Can you find that?

**Comment by green1052** [comment]
how

**Comment by piquark6046** [comment]
It is simple.
You can find the option causing your issue by turning off & on each option.

**Comment by green1052** [comment]
제 3자 인증 헤더 차단

**Review by piquark6046 — APPROVED** [review]

**Pull request merged**
