### PR TITLE
adcrap: unbreakables

### PR DESCRIPTION
**Pull request by seia-soto**
I am requesting you to **check the rules manually** since I don't know the exact functions that site operates. The rule will break the site functionalities because it prevents writes of additional contexts. However, the sites I put rules didn't break a lot to stop the original functionality of the website.

### CODE REVIEW

**Review by piquark6046 — CHANGES_REQUESTED** [review]
The scriptlet `aopw` of uBO is not the same function as `abort-on-property-read` of AdGuard.
Is it intended?

**Comment by JobcenterTycoon** [comment]
The filter for uBO works fine for me but the filter for Adguard breaks feedclick completely

**Comment by seia-soto** [comment]
> The scriptlet `aopw` of uBO is not the same function as `abort-on-property-read` of AdGuard. Is it intended?

Oo... It's typo error completely.

**Comment by seia-soto** [comment]
> The filter for uBO works fine for me but the filter for Adguard breaks feedclick completely

Can I get some URLs or screenshots to test myself in future? (If you tested with `aopr` on AG filter, it's typo error)

**Comment by JobcenterTycoon** [comment]
I taked the URLs from https://github.com/uBlockOrigin/uAssets/pull/13315

With your change it works fine now

**Comment by seia-soto** [comment]
Also, will update complete block for AdShield maybe tomorrow after calculating some side-effects. I am reverse analyzing new variant.

**Review by piquark6046 — APPROVED** [review]

**Pull request merged**
