### PR TITLE
ad: fmkorea.com, m.fmkorea.com

### PR DESCRIPTION
**Pull request by lidarbtc**
스크린샷 2023-09-14 23-41-24
This is an affiliate link.

스크린샷 2023-09-14 23-45-28
desktop(fmkorea.com)

스크린샷 2023-09-14 23-50-53
mobile(m.fmkorea.com)

### CODE REVIEW

**Comment by piquark6046** [comment]
Can you provide an example URL?
If you click a similar URL in https://www.fmkorea.com/best, you will be redirected to a community post in the same website.

---

If you want to get the original URL without any tracking parameter via an userscript, please refer https://github.com/List-KR/linkproduct-privacy.

**Comment by lidarbtc** [comment]
Yes, but only affiliate posts exist in the top_hotdeal class. Non-affiliate posts don't show up in the top_hotdeal class.

**Comment by lidarbtc** [comment]
Non-affiliate posts can only be viewed by directly accessing the hot deal board.

**Comment by piquark6046** [comment]
In `https://www.fmkorea.com/hotdeal`?

**Comment by lidarbtc** [comment]
Yes

**Comment by piquark6046** [comment]
Where?

<details><summary>Screenshot</summary>

image

</details>

**Comment by lidarbtc** [comment]
There was a miscommunication, the top_hotdeal class is linked to user posts on the hot deal board, but only posts from shopping malls affiliated with fmkorea belong to the top_hotdeal class.

Example: Musinsa is not affiliated with fmkorea, so Musinsa hot deal posts do not belong to the top_hotdeal class.

https://m.fmkorea.com/2179919759

DeepL로 번역함 (https://www.deepl.com/app/?utm_source=ios&utm_medium=app&utm_campaign=share-translation

**Comment by lidarbtc** [comment]
There was a miscommunication, the top_hotdeal class is linked to user posts on the hot deal board, but only posts from shopping malls affiliated with fmkorea belong to the top_hotdeal class.

Example: Musinsa is not affiliated with fmkorea, so Musinsa hot deal posts do not belong to the top_hotdeal class.

https://m.fmkorea.com/2179919759

**Review by piquark6046 — APPROVED** [review]

**Pull request merged**
