### PR TITLE
Block advertisement of Bandizip

### PR DESCRIPTION
**Pull request by green1052**

### CODE REVIEW

**Review by piquark6046 — CHANGES_REQUESTED** [review]
Cannot reproduce.
When is the advertisement request appeared?

**Comment by green1052** [comment]
https://kr.bandisoft.com/bandizip/

bandizip software

**Comment by piquark6046** [comment]
@green1052 I cannot find it.
<details>
<summary>Screenshot</summary>

Screenshot from 2022-02-09 18-04-00


</details>

**Comment by green1052** [comment]
<details>
<summary>Screenshot</summary>

image

</details>

**Review by piquark6046 — APPROVED** [review]

**Pull request merged**
