### PR TITLE
arca.live - Incorrect Blocking

### PR DESCRIPTION
**Pull request by QiAnCeNo**
https://github.com/List-KR/List-KR/pull/345

### CODE REVIEW

**Comment by seia-soto** [comment]
@piquark6046 I think to stop making new issues raised from the rule, we should make some statements on it. I agree with you in this case, please review at your own.

**Comment by QiAnCeNo** [comment]
I updated filter version.

**Comment by QiAnCeNo** [comment]
Updated version for commit of incorrect blocking for can be merge.

**Comment by seia-soto** [comment]
This PR is under evaluation to make better decision with maintainers.

Further action will be made after the evaluation.

I'll update the version when we're ready to take action.

**Pull request closed without merging**
