### PR TITLE
www.gmarket.co.kr - invalid rule

### PR DESCRIPTION
**Pull request by green1052**
this rule is break image

image

image

### CODE REVIEW

**Review by piquark6046 — CHANGES_REQUESTED** [review]
Please check the changes.

**Review by green1052 — COMMENTED** [review]
lgtm

**Review by piquark6046 — APPROVED** [review]

**Comment by green1052** [comment]
yes

**Comment by green1052** [comment]
@piquark6046 

sry this rule is not working in dns filter 
like adguard home

```
@@/^https:\/\/ad-img\.ebaykorea\.com\/ADS\/Contents_\/[0-9_]{19}\/[a-z0-9]{16}\.[A-Za-z]{3,4}$/$domain=gmarket.co.kr
```

**Comment by piquark6046** [comment]
Please take a look the following discussion:
https://github.com/List-KR/List-KR/discussions/300

**Comment by green1052** [comment]
yeah i forget that sry

**Pull request merged**
