### PR TITLE
feat: ygosu.com, inven.co.kr

### PR DESCRIPTION
**Pull request by seia-soto**
AdShield mitigation but not working on `ppss.kr` or `loawa.com`, I will not look details but here is a working version for `ygosu.com` and `inven.co.kr`.

Tested on AG macOS and uBO FF.

> I am recalculating my schedule and the school testing period is started yesterday. I'll start acting on ads maybe from next week actively.

### CODE REVIEW

**Review by piquark6046 — COMMENTED** [review]
Did you mean that this changes is needed for a visitor who does not use microShield?

**Comment by seia-soto** [comment]
> Did you mean that this changes is needed for a visitor who does not use microShield?

Yes, it works without microShield or userscript.

**Review by piquark6046 — CHANGES_REQUESTED** [review]
Is it intended?

<details>
<summary>Screenshots</summary>

Screenshot from 2022-06-29 18-22-21
Screenshot from 2022-06-29 18-24-07
Screenshot from 2022-06-29 18-24-23


</details>

**Comment by seia-soto** [comment]
> Is it intended?

Not really. I'll look on AdGuard.

<details>
<summary>Details</summary>


image

</details>

**Review by piquark6046 — APPROVED** [review]

**Pull request merged**
